version: '3'
services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - book-data:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - bookapp

  book-app:
    build: .
    depends_on: 
     - dbservice
    container_name: book-app
    environment:
     - spring.datasource.url=jdbc:mysql://dbservice:3306/book?createDatabaseIfNotExist=true&serverTimezone=UTC
     - spring.datasource.username=root
     - spring.datasource.password=root
    ports:
     - 8585:8585 
    networks:
     - bookapp

  book-ui:
    build: .
    depends_on: 
     - book-app
    container_name: book-ui
    ports:
      - 4200:9000
    
    networks:
      - bookapp

networks:
 bookapp:
 
volumes:
 book-data:
